---
- name: remove older Nginx Configuration
  file:
   path: "{{ item }}"
   state: absent
  with_items:
   - /etc/nginx/nginx.conf
   - /etc/nginx/conf.d/default.conf

- name: add nginx config
  template: 
   src: "{{ item.src }}"
   dest: "{{ item.des }}"
  with_items:
   - { src: '../templates/nginx.conf.j2' ,des: '/etc/nginx/nginx.conf' }
   - { src: '../templates/conf.d/default.conf.j2' ,des: '/etc/nginx/conf.d/default.conf' }

- name: start nginx
  service:
   name:  nginx
   state: started