---
- name: Nginx deployment playbook
  hosts: nginx-nodes        # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: root         # access remote server by root
  vars:
    nginx_ver:                            # nginx version to install
  roles:
    - dependencies
    - nginx